---
- name: Install Jenkins
  hosts: all
  become: yes
  become_user: root

  vars:
    docker_install: true
    jenkins_config_path: "{{ '/etc/sysconfig/jenkins' if ansible_facts['os_family'] == 'RedHat' else '/etc/default/jenkins' }}"

  roles:
    - os
    - java
    - jenkins
    - { role: docker, when: docker_install }
