---
- name: Delete old docker
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker 
    - docker-engine
    - docker.io
    - containerd
    - runc
- name: Add apt key Docker in Debian
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker to apt repository in Debian
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
- name: Install docker in Debian
  apt:
    name: "docker-ce"
    state: present
    update_cache: yes
- name: Restart docker in Debian
  service:
    name: docker
    state: restarted
- name: Add current user to docker group in Debian
  user:
    name: "{{ ansible_ssh_user|default(ansible_user_id) }}"
    group: docker
    append: yes
  ignore_errors: yes
